name: Jobs
description: Job plugin for bukkit
main: com.zford.jobs.Jobs
version: @VERSION@
author: phrstbrn
softdepend: [Permissions, iConomy, BOSEconomy, Stats]
commands:
    Jobs:
        description: Jobs
        usage: /jobs